apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodeapp
  name: {{ .Chart.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodeapp
    spec:
      containers:
      - image: hsabit01/nodeapp:0.1.0
        name: nodeapp
        ports:
        - containerPort: 3000
        resources: {}
status: {}
